language: php
warnings_are_errors: false

branches:
  except:
    - /^release-.*$/

env:
  global:
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"

matrix:
  include:
    - php: 7.4
      env:
        - DEPS=lowest
    - php: 7.4
      env:
        - DEPS=locked
    - php: 7.4
      env:
        - DEPS=latest
        - CHECK_PHAN=true

before_install:
  - travis_retry composer self-update
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - pecl install ast

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"

script:
  ## PHAN
  - if [[ $CHECK_PHAN == 'true' ]]; then composer phan ; fi

notifications:
  email:
    on_success: change
    on_failure: change
